#!/bin/bash
# Configurer le niveau de log
echo "Configuration du niveau de log..."

# Utiliser un niveau de log par défaut si non spécifié
LOG_LEVEL=${LOG_LEVEL:-info}
echo "Niveau de log : $LOG_LEVEL"
